[tool.poetry]
name = "paia"
version = "0.1.0"
description = ""
authors = ["potato"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.10"
mlgame = "^10.4.5.2"
scikit-learn = "^1.4.1.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
